services:
  jekyll:
    image: amirpourmand/al-folio:slim
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development  # Set Jekyll environment to development
